name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # run daily at midnight UTC
  workflow_dispatch:     # allow execution via manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: rootmannwright 
          outputs: dist

      - name: Commit snake.svg
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
